#!/bin/bash

function init {
  echo ""
  heading "Initializing"
  step "Checking vars"

  if [ "${JOB_NAME}" = "" ] ; then
    log "JOB_NAME is not defined. Expected something like: <app_name>-<buildstep>[-<environment>]" | red
    echo "${JOB_NAME}"
    exit 1
  fi

SHORTSHA=$(git rev-parse --short HEAD)
echo $SHORTSHA

}





